version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: cync_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cync
    ports:
      - '5432:5432'
    volumes:
      - cync_pgdata:/var/lib/postgresql/data

volumes:
  cync_pgdata:

